name: Deploy Frontend

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-front
      cancel-in-progress: true

    env:
      AWS_REGION: sa-east-1
      S3_BUCKET: centro-de-dia-aprender-a-volar
      CF_DIST_ID: E1R1NYZTEKJGP

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::277707101441:role/Movies-letterbox-Front
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync . s3://${{ env.S3_BUCKET }} --delete --exclude ".git/*" --exclude ".github/*"

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ env.CF_DIST_ID }} --paths "/*"
